name: update-documentation
on:
  workflow_run:
    workflows: [sphinx-build]
    branches: [master]
    types: [completed]
    
jobs:
  Documentation:
    name: sphinx
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: seanzhengw/sphinx-pages@master
        id: sphinx-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
          source_dir: docs
