name: sphinx-build
on:
  workflow_run:
    workflows: [tests]
    branches: [master]
    types: [completed]

jobs:
  generateFiles:
    name: Autodetect python files
    runs-on: ubuntu-latest
    if: github.event.workflow_run.conclusion == 'success'
    steps:
      - uses: actions/setup-python@v4
        with:
          python-version: "3.9"
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install flake8 sphinx       
      - uses: actions/checkout@v3
      - name: sphinx generate files
        run: |
          sphinx-apidoc -o docs/ source/
      - name: Commit and push changes
        run: |
          git config --global user.name "vpedrota"
          git config --global user.email "v.pedrota@unifesp.br"

          git add -A
          git commit -m "Generating Splhinx files" || true
          git push
          
